### PR TITLE
updated datamodel, basically finished

### PR DESCRIPTION
**Pull request by MingzeDou**

### CODE REVIEW

**Comment by petersenpeter** [comment]
This looks great Mingze. I will merge it into the main branch.

**Comment by petersenpeter** [comment]
Hi Mingze. 

I noticed that there are two Dissemination menu elements. Can I change this or do you prefer to do this yourself?

**Comment by MingzeDou** [comment]
Hi Peter,

Problem solved, also I updated a few files to make the data model part cleaner and more aligned.

**Comment by petersenpeter** [comment]
Perfect. Thanks.

**Pull request merged**
